fits_dir: !!python/str "S:"
date: !!python/str "20111210"
wavelength: !!python/int "171"
sub_reg_coords: [200,350,225,375]
coords_type: !!python/str "arc"
bin_frac: !!python/int "1"

temp_dir: !!python/str "S:"
mmap_derotate: !!python/str "y"
save_temp: !!python/str "n"

mmap_spectra: !!python/str "y"
num_segments: !!python/int "6"
