fits_dir: !!python/str "S:"
date: !!python/str "20130625"
wavelength: !!python/int "1700"
sub_reg_coords: [-180,-30,-375,-225]
coords_type: !!python/str "arc"
bin_frac: !!python/int "1"

temp_dir: !!python/str "S:"
mmap_derotate: !!python/str "y"
save_temp: !!python/str "n"

mmap_spectra: !!python/str "y"
num_segments: !!python/int "6"
